# Generated by Django 2.2.1 on 2019-05-11 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20190511_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='ava',
            field=models.CharField(default='https://cdn.pixabay.com/photo/2014/04/02/10/25/man-303792__340.png', max_length=100),
        ),
        migrations.AddField(
            model_name='teacher',
            name='ava',
            field=models.CharField(default='https://cdn.pixabay.com/photo/2014/04/02/10/25/man-303792__340.png', max_length=100),
        ),
    ]
