# Generated by Django 2.2.1 on 2019-05-12 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_answer_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='students',
            field=models.ManyToManyField(related_name='answers', to='database.Student'),
        ),
    ]
