# Generated by Django 2.2.1 on 2019-05-12 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20190512_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='current_activity',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='currant_lesson', to='database.Activity'),
        ),
    ]
